const typescript = require("@rollup/plugin-typescript");
const { nodeResolve } = require("@rollup/plugin-node-resolve");
const commonjs = require("@rollup/plugin-commonjs");
const fs = require("fs");

const isProd = process.env.BUILD === "production";
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
*/
`;

function copyStaticFiles() {
  return {
    name: "copy-static-files",
    buildStart() {
      fs.mkdirSync("build", { recursive: true });
      fs.copyFileSync("manifest.json", "build/manifest.json");
      fs.copyFileSync("styles.css", "build/styles.css");
    }
  };
}

module.exports = {
  input: "src/main.ts",
  output: {
    dir: "build",
    sourcemap: isProd ? false : "inline",
    sourcemapExcludeSources: isProd,
    format: "cjs",
    exports: "default",
    banner
  },
  external: ["obsidian", "crypto", "@codemirror/state", "@codemirror/view"],
  plugins: [
    copyStaticFiles(),
    typescript.default(),
    nodeResolve({ browser: false, preferBuiltins: true }),
    commonjs()
  ]
};
